version: '3'
services:
  app:
    build: ./app-elixir
    ports:
      - "4000:4000"
    volumes:
      - ./html:/var/www/html
  postgres:
    image: postgres:9.6.7-alpine
    volumes:
      - ./docker/pg:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: countdown_dev
    ports:
      - '5433:5432'
volumes:
  db: