version: '3'
services:
  app:
    build: ./app-elixir
    ports:
      - "4000:4000"
    volumes:
      - ../:/var/www/html/
    tty: true
  db:
    image: postgres:12
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
